training:
    A:
      sample: ./data/A.csv
      map: [0, 0, 0, 0, 0]
      alias: A
      boundary:
        - [2970, 3090]
        - [3470, 3590]
        - [3870, 3990]
        - [4315, 4435]
        - [4735, 4855]
        - [5095, 5215]
        - [5480, 5600]
        - [6250, 6370]
        - [6595, 6715]
    B:
      sample: ./data/B.csv
      map: [0, 0, 0, 0, 1]
      alias: B
      boundary:
        - [580, 690]
        - [990, 1100]
        - [1380, 1490]
        - [1760, 1870]
        - [2270, 2380]
        - [2690, 2800]
        - [3150, 3260]
        - [3590, 3700]
        - [4040, 4150]
    C:
      sample: ./data/C.csv
      map: [0, 0, 0, 1, 0]
      alias: C
      boundary:
        - [570, 650]
        - [980, 1060]
        - [1410, 1490]
        - [1840, 1920]
        - [2345, 2425]
        - [3430, 3510]
        - [4010, 4090]
        - [4540, 4620]
        - [5000, 5080]
    D:
      sample: ./data/D.csv
      map: [0, 0, 0, 1, 1]
      alias: D
      boundary:
          -[900, 1060]
          -[1250, 1510]
          -[1780, 1940]
          -[2240, 2400]
          -[2860, 3020]
          -[3350, 3510]
          -[3810, 3970]
          -[4220, 4380]
          -[4580, 4740]
    E:
      sample: ./data/E.csv
      map: [0, 0, 1, 0, 0]
      alias: E
      boundary:
          -[1410, 1550]
          -[1840, 1980]
          -[2235, 2375]
          -[2560, 2700]
          -[2900, 3040]
          -[3230, 3360]
          -[3550, 3690]
          -[3900, 4040]
          -[4380, 4520]
    F:
      sample: ./data/F.csv
      map: [0, 0, 1, 0, 1]
      alias: F
      boundary:
          -[1600, 1800]
          -[2200, 2400]
          -[2745, 2945]
          -[3420, 3620]
          -[4545, 4745]
          -[5045, 5245]
          -[5510, 5710]
          -[6210, 6410]
    G:
      sample: ./data/G.csv
      map: [0, 0, 1, 1, 0]
      alias: G
      boundary:
          -[1360, 1520]
          -[1880, 2040]
          -[2760, 2920]
          -[3200, 3340]
          -[3620, 3780]
          -[4240, 4400]
          -[4690, 4850]
          -[5095, 5255]
          -[5490, 5660]
    H:
      sample: ./data/H.csv
      map: [0, 0, 1, 1, 1]
      alias: H
      boundary:
          -[650, 810]
          -[1140, 1300]
          -[2150, 2310]
          -[2660, 2820]
          -[3160, 3320]
          -[4180, 4340]
    I:
      sample: ./data/I.csv
      map: [0, 1, 0, 0, 0]
      alias: I
      boundary:
          -[]
    J:
      sample: ./data/J.csv
      map: [0, 1, 0, 0, 1]
      alias: J
      boundary:
          -[]
    K:
      sample: ./data/K.csv
      map: [0, 1, 0, 1, 0]
      alias: K
      boundary:
          -[]
    L:
      sample: ./data/L.csv
      map: [0, 1, 0, 1, 1]
      alias: L
      boundary:
          -[]
    M:
      sample: ./data/M.csv
      map: [0, 1, 1, 0, 0]
      alias: M
      boundary:
          -[]
    N:
      sample: ./data/N.csv
      map: [0, 1, 1, 0, 1]
      alias: N
      boundary:
          -[]
    O:
      sample: ./data/O.csv
      map: [0, 1, 1, 1, 0]
      alias: O
      boundary:
          -[]
    P:
      sample: ./data/P.csv
      map: [0, 1, 1, 1, 1]
      alias: P
      boundary:
          -[]
    Q:
      sample: ./data/Q.csv
      map: [1, 0, 0, 0, 0]
      alias: Q
      boundary:
          -[]
    R:
      sample: ./data/R.csv
      map: [1, 0, 0, 0, 1]
      alias: R
      boundary:
          -[]
    S:
      sample: ./data/S.csv
      map: [1, 0, 0, 1, 0]
      alias: S
      boundary:
          -[]
    T:
      sample: ./data/T.csv
      map: [1, 0, 0, 1, 1]
      alias: T
      boundary:
          -[]
    U:
      sample: ./data/U.csv
      map: [1, 0, 1, 0, 0]
      alias: U
      boundary:
          -[]
    V:
      sample: ./data/V.csv
      map: [1, 0, 1, 0, 1]
      alias: V
      boundary:
          -[]
    W:
      sample: ./data/W.csv
      map: [1, 0, 1, 1, 0]
      alias: W
      boundary:
          -[]
    X:
      sample: ./data/X.csv
      map: [1, 0, 1, 1, 1]
      alias: X
      boundary:
          -[]
    Y:
      sample: ./data/Y.csv
      map: [1, 1, 0, 0, 0]
      alias: Y
      boundary:
          -[]
    Z:
      sample: ./data/Z.csv
      map: [1, 1, 0, 0, 1]
      alias: Z
      boundary:
          -[]
      