classifier:
    dtw:
        dimensions: [1, 8]
    knn:
        numberOfNeighbors: 2
        voter: distanceBasedVote
        
calibration:
        -
            Ra: [[-1, 0, 0.01], [-0.01, -1, 0.01], [0, -0.04, 1]]
            Ka: [[96, 0, 0], [0, 100, 0], [0, 0, 98]]
            Ba: [[1926], [2150], [1695]]
            offset: [1, 2, 3]
        -    
            Ra: [[-0.01, -1, 0.03], [-1, 0.01, -0.01], [0.02, -0.01, -1]]
            Ka: [[2.77, 0, 0], [0, 2.77, 0], [0, 0, 2.8]]
            Ba: [[1830], [1836], [1881]]
            offset: [4, 5, 6]
        -    
            Ra: [[1, 0, 0], [0, 1, 0], [0, 0, -1]]
            Ka: [[706, 0, 0], [0, 708, 0], [0, 0, 629]]
            Ba: [[-9], [149], [90]]
            offset: [7, 8, 9]
training:
    -
      sample: ./data/raw/A.csv
      map: [0, 0, 0, 0, 0]
      alias: A
      boundary:
        - [2964, 3098]
        - [3462, 3598]
        - [3867, 4000]
        - [4309, 4439]
        - [4722, 4865]
        - [5084, 5225]
        - [5473, 5620]
        - [5840, 5984]
        - [6240, 6373]
        - [6585, 6720]
    -
      sample: ./data/raw/B.csv
      map: [0, 0, 0, 0, 1]
      alias: B
      boundary:
        - [523, 705]
        - [938, 1110]
        - [1332, 1502]
        - [1717, 1872]
        - [2216, 2380]
        - [3093, 3263]
        - [3530, 3687]
        - [3997, 4158]
        - [4371, 4545]
        - [5186, 5344]
    -
      sample: ./data/raw/C.csv
      map: [0, 0, 0, 1, 0]
      alias: C
      boundary:
        - [558, 654]
        - [964, 1068]
        - [1409, 1508]
        - [1840, 1933]
        - [2330, 2430]
        - [2844, 2948]
        - [3427, 3510]
        - [4006, 4092]
        - [4529, 4617]
        - [5004, 5070]
    -
      sample: ./data/raw/D.csv
      map: [0, 0, 0, 1, 1]
      alias: D
      boundary:
        - [890, 1070]
        - [1344, 1529]
        - [1764, 1947]
        - [2231, 2400]
        - [2847, 3020]
        - [3338, 3510]
        - [3807, 3967]
        - [4210, 4373]
        - [4580, 4750]
        - [5566, 5741]
    -
      sample: ./data/raw/E.csv
      map: [0, 0, 1, 0, 0]
      alias: E
      boundary:
        - [1834, 2000]
        - [2234, 2400]
        - [2560, 2720]
        - [2900, 3055]
        - [3220, 3370]
        - [3550, 3701]
        - [3890, 4046]
        - [4380, 4544]
        - [5185, 5345]
        - [5943, 6093]
    -
      sample: ./data/raw/F.csv
      map: [0, 0, 1, 0, 1]
      alias: F
      boundary:
        - [1570, 1810]
        - [2190, 2415]
        - [2730, 2960]
        - [3380, 3625]
        - [4076, 4311]
        - [4511, 4748]
        - [5045, 5244]
        - [5488, 5717]
        - [6166, 6401]
        - [6745, 6971]
    -
      sample: ./data/raw/G.csv
      map: [0, 0, 1, 1, 0]
      alias: G
      boundary:
        - [1795, 2059]
        - [2300, 2515]
        - [2710, 2940]
        - [3139, 3366]
        - [3558, 3809]
        - [4159, 4410]
        - [4641, 4870]
        - [5030, 5255]
        - [5430, 5660]
        - [5900, 6122]
    -
      sample: ./data/raw/H.csv
      map: [0, 0, 1, 1, 1]
      alias: H
      boundary:
        - [1602, 1840]
        - [2065, 2325]
        - [2582, 2829]
        - [3075, 3341]
        - [3367, 3889]
        - [4120, 4332]
        - [4583, 4800]
        - [5029, 5259]
        - [6001, 6211]
        - [6403, 6616]
    -
      sample: ./data/raw/I.csv
      map: [0, 1, 0, 0, 0]
      alias: I
      boundary:
        - [1732, 2005]
        - [2133, 2400]
        - [2670, 2938]
        - [3130, 3370]
        - [3591, 3841]
        - [4040, 4253]
        - [4469, 4697]
        - [4844, 5085]
        - [5264, 5484]
        - [5646, 5882]
    -
      sample: ./data/raw/J.csv
      map: [0, 1, 0, 0, 1]
      alias: J
      boundary:
        - [760, 915]
        - [1355, 1505]
        - [2039, 2174]
        - [2508, 2650]
        - [3180, 3323]
        - [3840, 4001]
        - [4449, 4589]
        - [4901, 5025]
        - [5444, 5586]
        - [6010, 6158]
    -
      sample: ./data/raw/K.csv
      map: [0, 1, 0, 1, 0]
      alias: K
      boundary:
        - [550, 730]
        - [1201, 1418]
        - [1932, 2125]
        - [2790, 3001]
        - [3485, 3670]
        - [4051, 4237]
        - [4684, 4879]
        - [6172, 6392]
        - [7346, 7536]
        - [8019, 8240]
    -
      sample: ./data/raw/L.csv
      map: [0, 1, 0, 1, 1]
      alias: L
      boundary:
        - [1653, 1777]
        - [2280, 2390]
        - [2850, 2950]
        - [3460, 3564]
        - [4037, 4138]
        - [4634, 4742]
        - [5214, 5319]
        - [5727, 5830]
        - [6269, 6371]
        - [6903, 7005]
    -
      sample: ./data/raw/M.csv
      map: [0, 1, 1, 0, 0]
      alias: M
      boundary:
        - [660, 820]
        - [1625, 1786]
        - [2258, 2415]
        - [2757, 2926]
        - [3266, 3427]
        - [4123, 4267]
        - [4541, 4697]
        - [4889, 5053]
        - [5283, 5443]
        - [5685, 5854] 
    -
      sample: ./data/raw/N.csv
      map: [0, 1, 1, 0, 1]
      alias: N
      boundary:
        - [1330, 1480]
        - [1910, 2060]
        - [2630, 2780]
        - [3310, 3460]
        - [3900, 4050]
    -
      sample: ./data/raw/O.csv
      map: [0, 1, 1, 1, 0]
      alias: O
      boundary:
        - [880, 1030]
        - [1250, 1400]
        - [1650, 1800]
        - [2140, 2290]
        - [2630, 2780]
    -
      sample: ./data/raw/P.csv
      map: [0, 1, 1, 1, 1]
      alias: P
      boundary:
        - [1160, 1320]
        - [1700, 1860]
        - [2180, 2340]
        - [2680, 2840]
        - [3170, 3330]
    -
      sample: ./data/raw/Q.csv
      map: [1, 0, 0, 0, 0]
      alias: Q
      boundary:
        - [1130, 1340]
        - [1740, 1950]
        - [2360, 2570]
        - [3000, 3210]
        - [3680, 3890]
    -
      sample: ./data/raw/R.csv
      map: [1, 0, 0, 0, 1]
      alias: R
      boundary:
        - [2070, 2320]
        - [2700, 2950]
        - [3250, 3500]
        - [3850, 4100]
        - [4500, 4750]
    -
      sample: ./data/raw/S.csv
      map: [1, 0, 0, 1, 0]
      alias: S
      boundary:
        - [1150, 1330]
        - [1900, 2080]
        - [2520, 2700]
        - [3270, 3450]
        - [3950, 4130]
    -
      sample: ./data/raw/T.csv
      map: [1, 0, 0, 1, 1]
      alias: T
      boundary:
        - [1500, 1650]
        - [1990, 2140]
        - [2920, 3070]
        - [3340, 3490]
        - [3830, 3980]
    -
      sample: ./data/raw/U.csv
      map: [1, 0, 1, 0, 0]
      alias: U
      boundary:
        - [1340, 1490]
        - [1790, 1940]
        - [2180, 2330]
        - [2520, 2670]
        - [3050, 3200]
    -
      sample: ./data/raw/V.csv
      map: [1, 0, 1, 0, 1]
      alias: V
      boundary:
        - [2220, 2400]
        - [2595, 2775]
        - [2980, 3160]
        - [3320, 3500]
        - [3660, 3840]
    -
      sample: ./data/raw/W.csv
      map: [1, 0, 1, 1, 0]
      alias: W
      boundary:
        - [2090, 2290]
        - [2760, 2960]
        - [3280, 3480]
        - [3820, 4020]
        - [4320, 4520]
    -
      sample: ./data/raw/X.csv
      map: [1, 0, 1, 1, 1]
      alias: X
      boundary:
        - [850, 1000]
        - [1370, 1520]
        - [1800, 1950]
        - [2225, 2375]
        - [2650, 2800]
    -
      sample: ./data/raw/Y.csv
      map: [1, 1, 0, 0, 0]
      alias: Y
      boundary:
        - [660, 840]
        - [1150, 1330]
        - [1760, 1940]
        - [2260, 2440]
        - [2660, 2840]
    -
      sample: ./data/raw/Z.csv
      map: [1, 1, 0, 0, 1]
      alias: Z
      boundary:
        - [2530, 2730]
        - [2920, 3120]
        - [3330, 3530]
        - [3770, 3970]
        - [4160, 4360]
      