calibration:
        -
            Ra: [[-1, 0, 0.01], [-0.01, -1, 0.01], [0, -0.04, 1]]
            Ka: [[96, 0, 0], [0, 100, 0], [0, 0, 98]]
            Ba: [[1926], [2150], [1695]]
            offset: [1, 2, 3]
        -    
            Ra: [[-0.01, -1, 0.03], [-1, 0.01, -0.01], [0.02, -0.01, -1]]
            Ka: [[2.77, 0, 0], [0, 2.77, 0], [0, 0, 2.8]]
            Ba: [[1830], [1836], [1881]]
            offset: [4, 5, 6]
        -    
            Ra: [[1, 0, 0], [0, 1, 0], [0, 0, -1]]
            Ka: [[706, 0, 0], [0, 708, 0], [0, 0, 629]]
            Ba: [[-9], [149], [90]]
            offset: [7, 8, 9]
training:
    -
      sample: ./data/raw/A.csv
      map: [0, 0, 0, 0, 0]
      alias: A
      boundary:
        - [2970, 3090]
        - [3470, 3590]
        - [3870, 3990]
        - [4315, 4435]
        - [4735, 4855]
        - [5095, 5215]
        - [5480, 5600]
        - [6250, 6370]
        - [6595, 6715]
    -
      sample: ./data/raw/B.csv
      map: [0, 0, 0, 0, 1]
      alias: B
      boundary:
        - [580, 690]
        - [990, 1100]
        - [1380, 1490]
        - [1760, 1870]
        - [2270, 2380]
        - [2690, 2800]
        - [3150, 3260]
        - [3590, 3700]
        - [4040, 4150]
    -
      sample: ./data/raw/C.csv
      map: [0, 0, 0, 1, 0]
      alias: C
      boundary:
        - [570, 650]
        - [980, 1060]
        - [1410, 1490]
        - [1840, 1920]
        - [2345, 2425]
        - [3430, 3510]
        - [4010, 4090]
        - [4540, 4620]
        - [5000, 5080]
    -
      sample: ./data/raw/D.csv
      map: [0, 0, 0, 1, 1]
      alias: D
      boundary:
        - [900, 1060]
        - [1250, 1510]
        - [1780, 1940]
        - [2240, 2400]
        - [2860, 3020]
        - [3350, 3510]
        - [3810, 3970]
        - [4220, 4380]
        - [4580, 4740]
    -
      sample: ./data/raw/E.csv
      map: [0, 0, 1, 0, 0]
      alias: E
      boundary:
        - [1410, 1550]
        - [1840, 1980]
        - [2235, 2375]
        - [2560, 2700]
        - [2900, 3040]
        - [3230, 3360]
        - [3550, 3690]
        - [3900, 4040]
        - [4380, 4520]
    -
      sample: ./data/raw/F.csv
      map: [0, 0, 1, 0, 1]
      alias: F
      boundary:
        - [1600, 1800]
        - [2200, 2400]
        - [2745, 2945]
        - [3420, 3620]
        - [4545, 4745]
        - [5045, 5245]
        - [5510, 5710]
        - [6210, 6410]
    -
      sample: ./data/raw/G.csv
      map: [0, 0, 1, 1, 0]
      alias: G
      boundary:
        - [1360, 1520]
        - [1880, 2040]
        - [2760, 2920]
        - [3200, 3340]
        - [3620, 3780]
        - [4240, 4400]
        - [4690, 4850]
        - [5095, 5255]
        - [5490, 5660]
    -
      sample: ./data/raw/H.csv
      map: [0, 0, 1, 1, 1]
      alias: H
      boundary:
        - [650, 820]
        - [1140, 1310]
        - [2150, 2320]
        - [2660, 2830]
        - [3160, 3330]
        - [4180, 4340]
    -
      sample: ./data/raw/I.csv
      map: [0, 1, 0, 0, 0]
      alias: I
      boundary:
        - [1280, 1550]
        - [1735, 2005]
        - [2140, 2410]
        - [2670, 2940]
        - [3120, 3390]
    -
      sample: ./data/raw/J.csv
      map: [0, 1, 0, 0, 1]
      alias: J
      boundary:
        - [2010, 2180]
        - [2490, 2660]
        - [3160, 3330]
        - [3820, 3990]
        - [4420, 4590]
    -
      sample: ./data/raw/K.csv
      map: [0, 1, 0, 1, 0]
      alias: K
      boundary:
        - [540, 740]
        - [1210, 1410]
        - [1930, 2130]
        - [2790, 2990]
        - [3480, 3680]
    -
      sample: ./data/raw/L.csv
      map: [0, 1, 0, 1, 1]
      alias: L
      boundary:
        - [1020, 1130]
        - [1660, 1770]
        - [2280, 2390]
        - [2850, 2960]
        - [3460, 3570]
    -
      sample: ./data/raw/M.csv
      map: [0, 1, 1, 0, 0]
      alias: M
      boundary:
        - [660, 830]
        - [1620, 1790]
        - [2250, 2420]
        - [2760, 2930]
        - [3260, 3430]
    -
      sample: ./data/raw/N.csv
      map: [0, 1, 1, 0, 1]
      alias: N
      boundary:
        - [1330, 1480]
        - [1910, 2060]
        - [2630, 2780]
        - [3310, 3460]
        - [3900, 4050]
    -
      sample: ./data/raw/O.csv
      map: [0, 1, 1, 1, 0]
      alias: O
      boundary:
        - [880, 1030]
        - [1250, 1400]
        - [1650, 1800]
        - [2140, 2290]
        - [2630, 2780]
    -
      sample: ./data/raw/P.csv
      map: [0, 1, 1, 1, 1]
      alias: P
      boundary:
        - [1160, 1320]
        - [1700, 1860]
        - [2180, 2340]
        - [2680, 2840]
        - [3170, 3330]
    -
      sample: ./data/raw/Q.csv
      map: [1, 0, 0, 0, 0]
      alias: Q
      boundary:
        - [1130, 1340]
        - [1740, 1950]
        - [2360, 2570]
        - [3000, 3210]
        - [3680, 3890]
    -
      sample: ./data/raw/R.csv
      map: [1, 0, 0, 0, 1]
      alias: R
      boundary:
        - [2070, 2320]
        - [2700, 2950]
        - [3250, 3500]
        - [3850, 4100]
        - [4500, 4750]
    -
      sample: ./data/raw/S.csv
      map: [1, 0, 0, 1, 0]
      alias: S
      boundary:
        - [1150, 1330]
        - [1900, 2080]
        - [2520, 2700]
        - [3270, 3450]
        - [3950, 4130]
    -
      sample: ./data/raw/T.csv
      map: [1, 0, 0, 1, 1]
      alias: T
      boundary:
        - [1500, 1650]
        - [1990, 2140]
        - [2920, 3070]
        - [3340, 3490]
        - [3830, 3980]
    -
      sample: ./data/raw/U.csv
      map: [1, 0, 1, 0, 0]
      alias: U
      boundary:
        - [1340, 1490]
        - [1790, 1940]
        - [2180, 2330]
        - [2520, 2670]
        - [3050, 3200]
    -
      sample: ./data/raw/V.csv
      map: [1, 0, 1, 0, 1]
      alias: V
      boundary:
        - [2220, 2400]
        - [2595, 2775]
        - [2980, 3160]
        - [3320, 3500]
        - [3660, 3840]
    -
      sample: ./data/raw/W.csv
      map: [1, 0, 1, 1, 0]
      alias: W
      boundary:
        - [2090, 2290]
        - [2760, 2960]
        - [3280, 3480]
        - [3820, 4020]
        - [4320, 4520]
    -
      sample: ./data/raw/X.csv
      map: [1, 0, 1, 1, 1]
      alias: X
      boundary:
        - [850, 1000]
        - [1370, 1520]
        - [1800, 1950]
        - [2225, 2375]
        - [2650, 2800]
    -
      sample: ./data/raw/Y.csv
      map: [1, 1, 0, 0, 0]
      alias: Y
      boundary:
        - [660, 840]
        - [1150, 1330]
        - [1760, 1940]
        - [2260, 2440]
        - [2660, 2840]
    -
      sample: ./data/raw/Z.csv
      map: [1, 1, 0, 0, 1]
      alias: Z
      boundary:
        - [2530, 2730]
        - [2920, 3120]
        - [3330, 3530]
        - [3770, 3970]
        - [4160, 4360]
      