classifier:
    dtw:
        dimensions: [1, 8]
    knn:
        K: 5
        
calibration:
        -
            Ra: [[-1, 0, 0.01], [-0.01, -1, 0.01], [0, -0.04, 1]]
            Ka: [[96, 0, 0], [0, 100, 0], [0, 0, 98]]
            Ba: [[1926], [2150], [1695]]
            offset: [1, 2, 3]
        -    
            Ra: [[-0.01, -1, 0.03], [-1, 0.01, -0.01], [0.02, -0.01, -1]]
            Ka: [[2.77, 0, 0], [0, 2.77, 0], [0, 0, 2.8]]
            Ba: [[1830], [1836], [1881]]
            offset: [4, 5, 6]
        -    
            Ra: [[1, 0, 0], [0, 1, 0], [0, 0, -1]]
            Ka: [[706, 0, 0], [0, 708, 0], [0, 0, 629]]
            Ba: [[-9], [149], [90]]
            offset: [7, 8, 9]
training:
    -
      sample: ./data/raw/A.csv
      map: [0, 0, 0, 0, 0]
      alias: A
      boundary:
        - [2964, 3098]
        - [3462, 3598]
        - [3867, 4000]
        - [4309, 4439]
        - [4722, 4865]
        - [5084, 5225]
        - [5473, 5620]
        - [5840, 5984]
        - [6240, 6373]
    -
      sample: ./data/raw/B.csv
      map: [0, 0, 0, 0, 1]
      alias: B
      boundary:
        - [523, 705]
        - [938, 1110]
        - [1332, 1502]
        - [1717, 1872]
        - [2216, 2380]
        - [3093, 3263]
        - [3530, 3687]
        - [3997, 4158]
        - [4371, 4545]
    -
      sample: ./data/raw/C.csv
      map: [0, 0, 0, 1, 0]
      alias: C
      boundary:
        - [558, 654]
        - [964, 1068]
        - [1409, 1508]
        - [1840, 1933]
        - [2330, 2430]
        - [2844, 2948]
        - [3427, 3510]
        - [4006, 4092]
        - [4529, 4617]
    -
      sample: ./data/raw/D.csv
      map: [0, 0, 0, 1, 1]
      alias: D
      boundary:
        - [1344, 1529]
        - [1764, 1947]
        - [2231, 2400]
        - [2847, 3020]
        - [3338, 3510]
        - [3807, 3967]
        - [4210, 4373]
        - [4580, 4750]
        - [5566, 5741]
    -
      sample: ./data/raw/E.csv
      map: [0, 0, 1, 0, 0]
      alias: E
      boundary:
        - [1834, 2000]
        - [2234, 2400]
        - [2560, 2720]
        - [2900, 3055]
        - [3220, 3370]
        - [3550, 3701]
        - [3890, 4046]
        - [4380, 4544]
        - [5185, 5345]
    -
      sample: ./data/raw/F.csv
      map: [0, 0, 1, 0, 1]
      alias: F
      boundary:
        - [1570, 1810]
        - [2190, 2415]
        - [2730, 2960]
        - [3380, 3625]
        - [4076, 4311]
        - [4511, 4748]
        - [5045, 5244]
        - [5488, 5717]
        - [6166, 6401]
    -
      sample: ./data/raw/G.csv
      map: [0, 0, 1, 1, 0]
      alias: G
      boundary:
        - [1795, 2059]
        - [2300, 2515]
        - [2710, 2940]
        - [3139, 3366]
        - [3558, 3809]
        - [4159, 4410]
        - [4641, 4870]
        - [5030, 5255]
        - [5430, 5660]
    -
      sample: ./data/raw/H.csv
      map: [0, 0, 1, 1, 1]
      alias: H
      boundary:
        - [1602, 1840]
        - [2065, 2325]
        - [2582, 2829]
        - [3075, 3341]
        - [3367, 3889]
        - [4120, 4332]
        - [4583, 4800]
        - [5029, 5259]
        - [6001, 6211]
    -
      sample: ./data/raw/I.csv
      map: [0, 1, 0, 0, 0]
      alias: I
      boundary:
        - [1732, 2005]
        - [2133, 2400]
        - [2670, 2938]
        - [3130, 3370]
        - [3591, 3841]
        - [4040, 4253]
        - [4469, 4697]
        - [4844, 5085]
        - [5264, 5484]
    -
      sample: ./data/raw/J.csv
      map: [0, 1, 0, 0, 1]
      alias: J
      boundary:
        - [760, 915]
        - [1355, 1505]
        - [2039, 2174]
        - [2508, 2650]
        - [3180, 3323]
        - [3840, 4001]
        - [4449, 4589]
        - [4901, 5025]
        - [5444, 5586]
    -
      sample: ./data/raw/K.csv
      map: [0, 1, 0, 1, 0]
      alias: K
      boundary:
        - [550, 730]
        - [1201, 1418]
        - [1932, 2125]
        - [2790, 3001]
        - [3485, 3670]
        - [4051, 4237]
        - [4684, 4879]
        - [6172, 6392]
        - [7346, 7536]
    -
      sample: ./data/raw/L.csv
      map: [0, 1, 0, 1, 1]
      alias: L
      boundary:
        - [1653, 1777]
        - [2280, 2390]
        - [2850, 2950]
        - [3460, 3564]
        - [4037, 4138]
        - [4634, 4742]
        - [5214, 5319]
        - [5727, 5830]
        - [6269, 6371]
    -
      sample: ./data/raw/M.csv
      map: [0, 1, 1, 0, 0]
      alias: M
      boundary:
        - [660, 820]
        - [1625, 1786]
        - [2258, 2415]
        - [2757, 2926]
        - [3266, 3427]
        - [4123, 4267]
        - [4541, 4697]
        - [4889, 5053]
        - [5283, 5443]
    -
      sample: ./data/raw/N.csv
      map: [0, 1, 1, 0, 1]
      alias: N
      boundary:
        - [700, 850]  
        - [1328, 1473]
        - [1917, 2045]
        - [2629, 2772]
        - [3318, 3434]
        - [3886, 4035]
        - [4387, 4537]
        - [4908, 5050]
        - [5321, 5469]
    -
      sample: ./data/raw/O.csv
      map: [0, 1, 1, 1, 0]
      alias: O
      boundary:
        - [874, 1042]
        - [1647, 1818]
        - [2140, 2298]
        - [2659, 2791]
        - [3104, 3265]
        - [3609, 3783]
        - [4618, 4767]
        - [5080, 5193]
        - [5519, 5626]
    -
      sample: ./data/raw/P.csv
      map: [0, 1, 1, 1, 1]
      alias: P
      boundary:
        - [1032, 1312]
        - [1548, 1864]
        - [2067, 2336]
        - [3076, 3346]
        - [3561, 3813]
        - [4042, 4284]
        - [5021, 5317]
        - [5467, 5763]
        - [5986, 6273]
    -
      sample: ./data/raw/Q.csv
      map: [1, 0, 0, 0, 0]
      alias: Q
      boundary:
        - [1130, 1332]
        - [1737, 1945]
        - [2368, 2560]
        - [3006, 3210]
        - [3689, 3870]
        - [4267, 4436]
        - [4823, 5016]
        - [5439, 5623]
        - [6001, 6173]
    -
      sample: ./data/raw/R.csv
      map: [1, 0, 0, 0, 1]
      alias: R
      boundary:
        - [2080, 2320]
        - [2700, 2931]
        - [3271, 3489]
        - [3871, 4100]
        - [4490, 4728]
        - [5019, 5208]
        - [5512, 5708]
        - [6525, 6746]
        - [8208, 8418]
    -
      sample: ./data/raw/S.csv
      map: [1, 0, 0, 1, 0]
      alias: S
      boundary:
        - [1945, 2054]
        - [2558, 2671]
        - [3305, 3420]
        - [4004, 4107]
        - [4575, 4704]
        - [5588, 5707]
        - [6033, 6150]
        - [6458, 6584]
        - [6862, 6980]
    -
      sample: ./data/raw/T.csv
      map: [1, 0, 0, 1, 1]
      alias: T
      boundary:
        - [949, 1076]  
        - [1538, 1659]
        - [2034, 2153]
        - [2477, 2592]
        - [2953, 3079]
        - [3363, 3500]
        - [3862, 4001]
        - [4344, 4471]
        - [5263, 5405]
    -
      sample: ./data/raw/U.csv
      map: [1, 0, 1, 0, 0]
      alias: U
      boundary:
        - [1355, 1490]
        - [1797, 1921]
        - [2204, 2313]
        - [3058, 3200]
        - [3539, 3667]
        - [3967, 4113]
        - [4387, 4518]
        - [4899, 5040]
        - [5720, 5849]
    -
      sample: ./data/raw/V.csv
      map: [1, 0, 1, 0, 1]
      alias: V
      boundary:
        - [704, 888]
        - [1341, 1507]
        - [1813, 1978]
        - [2237, 2413]
        - [2603, 2769]
        - [3334, 3488]
        - [3663, 3834]
        - [4043, 4184]
        - [4362, 4512]
    -
      sample: ./data/raw/W.csv
      map: [1, 0, 1, 1, 0]
      alias: W
      boundary:
        - [2092, 2295]
        - [2784, 2943]
        - [3306, 3458]
        - [3835, 4006]
        - [4332, 4487]
        - [5293, 5461]
        - [5751, 5919]
        - [6193, 6334]
        - [6594, 6741]
    -
      sample: ./data/raw/X.csv
      map: [1, 0, 1, 1, 1]
      alias: X
      boundary:
        - [367, 532]  
        - [855, 1008]
        - [1391, 1537]
        - [1808, 1961]
        - [2229, 2375]
        - [2656, 2811]
        - [3118, 3278]
        - [3545, 3696]
        - [3961, 4103]
    -
      sample: ./data/raw/Y.csv
      map: [1, 1, 0, 0, 0]
      alias: Y
      boundary:
        - [671, 818]
        - [1158, 1323]
        - [1767, 1914]
        - [2265, 2414]
        - [2670, 2839]
        - [3072, 3229]
        - [3518, 3691]
        - [4017, 4174]
        - [5019, 5142]
    -
      sample: ./data/raw/Z.csv
      map: [1, 1, 0, 0, 1]
      alias: Z
      boundary:
        - [446, 610]
        - [898, 1049]
        - [1483, 1601]
        - [2001, 2131]
        - [2577, 2725]
        - [2948, 3094]
        - [3361, 3506]
        - [3805, 3948]
        - [4189, 4349]      